export const PRESIDENTIAL_SEARCH_EMBEDDING_MODEL = "mistral-embed";
export const PRESIDENTIAL_SEARCH_EMBEDDING_DIMENSIONS = 1024;
export const PRESIDENTIAL_SEARCH_EMBEDDING_MAX_CHARACTERS = 500;
export const PRESIDENTIAL_SEARCH_EMBEDDING_BATCH_SIZE = 16;
export const PRESIDENTIAL_SEARCH_EMBEDDING_VERSION = "presidential-search-v1";
